# DATOS DE CONEXIÓN A LA BASE DE DATOS
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:51531/railway
spring.datasource.username=root
spring.datasource.password=dWFxpiLzhnzYIPvBNNRXWcYtCCuECfBr

# CONFIGURACIÓN JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# mysql://root:JxTXUwauHEOkIOfWlASKBKOpjPzRlwBL@metro.proxy.rlwy.net:15193/railway


# confuguración para el envio de correos
# https://myaccount.google.com/apppasswords
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alejandromocse01@gmail.com
spring.mail.password=caxh wbcc xmlv vrva
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=${PORT:8080}